apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      name: jenkins
      namespace: jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: azima/jenkins-docker:latest
          resources:
            limits:
              cpu: 300m
              memory: 800Mi
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
          ports:
            - name: jenkins
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
