apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      name: jenkins
      namespace: jenkins
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: azima/jenkins-docker:latest
          resources: {}
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - name: jenkins
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: jenkins-data
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: jenkins-storage