apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jenkins
  labels:
    app: jenkins
  name: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: azima/jenkins-docker:latest
          name: jenkins
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
