apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
type: Opaque
data:
 postgresql-postgres-password: YXppbWEK
 postgresql-password: YXppbWEK
 SONAR_WEB_SYSTEMPASSCODE: YXppbWEK