apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: jenkins
    - name: agents
      protocol: TCP
      port: 9000
      targetPort: agents
