apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: sonarqube
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app: sonarqube
    release: sonarqube
  type: LoadBalancer
