apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: sonarqube
  labels:
    app: sonarqube
data:
  sonar.jdbc.username: sonar
  sonar.jdbc.url: jdbc:postgresql://sonarqube-postgresql/sonar
