apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: sonarqube
  labels:
    app: sonarqube
data:
  sonar.jdbc.username: sonar
  # sonar.jdbc.url: jdbc:postgresql://sonarqube-postgresql:5432/sonar
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: elk.azima.website
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kibana
                port:
                  number: 3000
    - host: sonarqube.azima.website
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarqube-sonarqube
                port:
                  number: 5000
---

kind: Service
apiVersion: v1
metadata:
  name: sonarqube-sonarqube
spec:
  type: ExternalName
  externalName: sonarqube-sonarqube.sonarqube.svc.cluster.local