---
BRANCH: jenkins
DIRECTORY: jenkins
GITHUB_REPO: https://github.com/Mahmoudalziem/Full-Arc-Microservices-Devops.git
JENKINS_ACCESS: kubectl get svc jenkins -n jenkins -o jsonpath='{.status.loadBalancer.ingress[0]}'
JENKINS_ACCESS_HOSTNAME: kubectl get svc jenkins -n jenkins -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
POD_NAME:  kubectl get pods -l app=jenkins -n jenkins -o name | cut -d / -f2
JENKINS_PASSWORD: kubectl exec $({{ POD_NAME }}) -n jenkins cat /var/jenkins_home/secrets/initialAdminPassword 