---
- name: Pull Microservices Github
  git:
    repo: https://github.com/Mahmoudalziem/Full-Arc-Microservices-Devops.git
    dest: application
    version: microservices
    clone: yes

- name: Get files on remote machine
  find:
    paths: application
    patterns: "*.yaml"
  register: jenkins_files

- name: Install Microservices
  k8s:
    src: "{{ item }}"
  loop: "{{ jenkins_files|json_query('files[].path') }}"