---

#### Update Operating System Dependencies

- name: Update system Dependencies
  command: apt update -y

#### Install Aws Command Line

- name: Install Aws Cli
  apt:
    name: "{{ item }}"
    state: present 
  loop:
    - awscli

#### Cofigure Aws Programmtic Access

- name: Configure AWS.
  shell: aws configure set {{ item.NAME }} {{ item.VALUE }}
  no_log: True
  loop:
    - NAME: aws_access_key_id
      VALUE: "{{ ACCESS_KEY }}"
    - NAME: aws_secret_access_key
      VALUE: "{{ SECRET_ACCESS_KEY }}"
    - NAME: region
      VALUE: "{{ REGION }}"
    - NAME: format
      VALUE: "{{ FORMAT }}"
  become_user: "{{ SYSTEM_USER }}"
  changed_when: false

#### Cofigure Aws Access EKS => (Elastic Kubernetes Service)

- name: Configure Eks.
  command: aws eks update-kubeconfig --region {{ REGION }} --name {{ CLUSTER_NAME }}
  notify: success