apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test
  labels:
    app: test
  annotation:
    author: "Mahmoud Abd Alziem"
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: APP_TEST
              valueFrom:
                configMapKeyRef:
                  name: app-test
                  key: app-test
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-test
          ports:
            - name: DB_HOST
              containerPort: 8080
              protocol: HTTP
          volumeMount:
            - name: localvolume
              mountPath: /var/run/docker.sock
      volumes:
        - name: localvolume
          path: /var/run/docker.sock
      restartPolicy: Always

---

#/// NameSpace

apiVerison: v1
kind: Namespace
metadata:
  name: jenknis
  labels:
    app: jenknis
  anotations:
    author: "Mahmoud Abd Alziem"

---

#////ConfigMapJenkins

apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: jenknis-configmap
  labels:
    app: jenkins-configmap
data:
  DB_HOST: 127.0.0.01
  DB_PASSWORD: azima

---
#/// Secrets

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  labels:
    app: jenkins-secret
data:
  DB_HOST: MTI3LjAuMC4xCg==
  DB_PASSWORD: YXppbWEK

---

# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: serviceaccount
  namespace: jenkins
---


---
